export type LoanTypes =
  | "GET-ALL-EMPLOYEE-LOAN"
  | "GET_EMPLOYEE-LOAN-SUMMARY"
  | "CREATE-BULK-EMPLOYEE-LOAN"
  | "UPDATE-AFTER-GENERATE-SALARY";

export const GETALLEMPLOYEELOAN: LoanTypes = "GET-ALL-EMPLOYEE-LOAN";

export const GETEMPLOYEELOANSUMMARY: LoanTypes = "GET_EMPLOYEE-LOAN-SUMMARY";

export const CREATEBULKEMPLOYEELOAN: LoanTypes = "CREATE-BULK-EMPLOYEE-LOAN";

export const UPDATEAFTERSALARY: LoanTypes = "UPDATE-AFTER-GENERATE-SALARY";
